apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xplane
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.13.2
  - repoURL: https://github.com/noahburrell0/akp-crossplane-demo.git
    targetRevision: main
    path: configs/xplane
    directory:
      recurse: true
  destination:
    name: demo1
    namespace: crossplane-system

